export const speakerObj = {
    id: 'speaker',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: ['Todays Speaker'],
    headline: ['Nadim Rahman'],
    description: [' "Hi, i\'m Nad. I\'m a Computer Science Masters student at Imperial College London! In this podcast, i\'ll be telling you my top 5 reasons (in no particular order) for wanting to join Spotify. You can also check out the projects i\'ve been working on at the end of this podcast." '],
    imgStart: true,
    img: require('../../images/illustration-speaker.png').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "reason1",
};

export const reasonOneContentObj = {
    id: 'reasonOneContent',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: [''],
    headline: ['MUSIC.'],
    description: [' "Music is a big part of my life and most of my day will either involve listening or playing music! I enjoy playing with instruments, such as the ukelele and guitar, as well as DJing and remixing different songs together. Given my passion for this creative industry, an opportunity at Spotify felt fitting to me." '],
    buttonLabel: ['Learn More'],
    imgStart: true,
    img: require('../../images/illustration-dj.png').default,
    alt: 'dj',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "reason2",
};

export const reasonTwoContentObj = {
    id: 'reasonTwoContent',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: [''],
    headline: ['COMPANY CULTURE.'],
    description: [' "The company genuinely care for your wellbeing and the workplace feels like a community that I hope to be part of. This is particularly important to me as a healthy worklife-balance allows me to do my best work. From attending Spotify\'s career events, I know that even as an intern, I have the opportunity to express my ideas and be heard. Additionally, the company are committed to combat climate change, such as using their platform to raise awareness, to also developing efficiently to cut down emmissions. Such actions make me motivated to work for Spotify, as I want to do my part to help save the planet." '],
    buttonLabel: ['Learn More'],
    imgStart: true,
    img: require('../../images/illustration-sustainable.png').default,
    alt: 'dj',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "reason3",
};

export const reasonThreeContentObj = {
    id: 'reasonThreeContent',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: [''],
    headline: ['The App.'],
    description: [' "I have been an avid Spotify fan for years now. I use this app when travelling, working out, studying, partying or even to help me sleep. The app has revolutionised how we listen to music and podcasts since the app is able to harness the vast amount of data it has to create meaningful reccomendations that have so often allowed me to find great content. I want to be able to be able to have a say in the development of the most successful audio streaming and media service in the World." '],
    buttonLabel: ['Learn More'],
    imgStart: true,
    img: require('../../images/illustration-app.png').default,
    alt: 'app',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "reason4",
};

export const reasonFourContentObj = {
    id: 'reasonFourContent',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: [''],
    headline: ['Learning.'],
    description: [' "I’ll be working with talented individuals who I can learn more from and collaborate with existing employees at the company. They were all hired for a reason, and I’d thrive on the chance to work with people who are all passionate about the future success of the Spotify brand. It is comforting hearing from previous interns that everyone is open to help you with problems and make you the best possible you. I would take this to my advantage to improve on my skills, whether it be involved with coding, managing, or presenting." '],
    buttonLabel: ['Learn More'],
    imgStart: true,
    img: require('../../images/illustration-learn.png').default,
    alt: 'learn',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "reason5",
};

export const reasonFiveContentObj = {
    id: 'reasonFiveContent',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: [''],
    headline: ['Technology.'],
    description: [' "I\'m passionate about all things revolved around technology as I love problem solving, and technology is integral to what Spotify do. The company already have developed some innovative tech over the years, and they have the resources to scale this even further." '],
    buttonLabel: ['Learn More'],
    imgStart: true,
    img: require('../../images/illustration-robot.png').default,
    alt: 'wrapped',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "wrappedObj",
};

export const wrappedObj = {
    id: 'wrappedObj',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: [''],
    headline: ['#PODCASTWRAPPED.'],
    description: [' "Aaanddd that comes to an end to this podcast, I hope you enjoyed it! All the illustrations used for this podcast (except for the vector images below) were drawn using ProCreate. This website was created using React, CSS, and Javascript. If you want to learn more about the projects I have undertaken, feel free to click/scroll below :) " '],
    buttonLabel: ['Learn More'],
    imgStart: true,
    img: require('../../images/illustration-wrapped.png').default,
    alt: 'dj',
    dark: false,
    primary: false,
    darkText: true,
    hasButton: true,
    buttonId: "projects",
};

export const homeObjThree = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transctions without getting charged any fees.',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'Paper',
    dark: false,
    primary: false,
    darkText: true
};